server:
  port: 8086
  servlet:
    context-path: /NCForecast
spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:sqlserver://111.198.29.34:3348;DatabaseName=Meteo_Hainan;integratedSecurity=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: dclw@2019

mybatis:
  mapper-locations: "classpath:mapper/*.xml"

#Spring boot视图配置
#http://127.0.0.1:8086/NCForecast/NCparse/readGribToSql
spring.mvc.view:
  prefix: /WEB-INF/jsp/
  suffix: .jsp
